version: '3'
services:
    usagi-chan:
        build: .
        volumes:
            - .:/Usagi
        restart: "no"
        ports:
            - "8080:8080"
        env_file:
            - usagi-variables.env