services:
    usagi-chan:
        build: .
#        volumes:
#          - .:/Usagi
        env_file:
            - stack.env
        depends_on:
          - postgres

    postgres:
        image: pgvector/pgvector:pg17
        env_file:
            - stack.env
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
  pg_data:
