[pytest]
filterwarnings =
    ignore::DeprecationWarning:
    ignore:.*GenericFunction.*already registered.*:sqlalchemy.exc.SAWarning
    ignore:.*The NumPy module was reloaded.*:UserWarning
    ignore:.*his declarative base already contains a class with the same class*:sqlalchemy.exc.SAWarning