name: Test & Deploy to CapRover

on:
  push:
    branches: [ "universal" ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment: Caprover

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

#    - name: Install CapRover CLI
#      run: npm install -g caprover
#
#    - name: Deploy to CapRover
#      if: success()
#      run: |
#        caprover deploy \
#          --caproverUrl '${{ secrets.CAPROVER_SERVER }}' \
#          --appToken '${{ secrets.APP_TOKEN }}' \
#          --appName '${{ secrets.APP_NAME }}' \
#          -b universal
